version: '3.9'
services:
    db:
        image: mysql:8.0
        restart: always
        ports:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - mydatabasedata:/var/lib/mysql
            - ./init:/docker-entrypoint-initdb.d
    web_app:
        build: .
        restart: always
        ports:
            - 3002:3000
        environment:
            PORT: 3000
volumes:
    mydatabasedata:
