create database lgquizz character set UTF8mb4 collate utf8mb4_bin;
drop table if exists lgquizz.TestResponses;
drop table if exists lgquizz.TestParticipants;
drop table if exists lgquizz.TestContents;
drop table if exists lgquizz.Tests;
drop table if exists lgquizz.Responses;
drop table if exists lgquizz.Exercises;
drop table if exists lgquizz.Problems;
drop table if exists lgquizz.Lessons;
drop table if exists lgquizz.Users;
drop table if exists lgquizz.Categories;


create table lgquizz.Users(
	id_user int primary key auto_increment,
    email varchar(50) unique not null,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    password varchar(50) not null
);

create table lgquizz.Lessons(
	id_lesson int primary key auto_increment,
    lesson_name varchar(50) not null,
    lesson_description varchar(500)
);

create table lgquizz.Categories(
	id_category int primary key auto_increment,
    category_name varchar(50) not null,
    category_description varchar(500)
);

create table lgquizz.Problems(
	id_problem int primary key auto_increment,
    id_lesson int not null,
    id_category int not null,
    problem_text varchar(100) not null,
	foreign key (id_lesson) references lgquizz.Lessons(id_lesson),
    foreign key (id_category) references lgquizz.Categories(id_category)
);

create table lgquizz.Exercises(
	id_exercise int primary key auto_increment,
    id_problem int not null,
    content varchar(250) not null,
    mark double not null,
    constraint `EXERCISE_CHECK_FAIL` check(mark<=10 AND mark>=0),
    foreign key (id_problem) references lgquizz.Problems(id_problem)
);
create table lgquizz.Responses(
	id_response int primary key auto_increment,
    id_exercise int not null ,
    content varchar(250) not null,
    percentage double,
    foreign key (id_exercise) references Exercises(id_exercise),
    constraint `RESP_CHECK_FAIL` check(percentage<=1 AND percentage>=0),
    constraint `UNIQUE_ANS` unique(id_exercise,content)
);

create table lgquizz.Tests(
	id_test int primary key auto_increment,
    test_name varchar(100) unique,
    restricted bool not null,
    expiration_date timestamp
);

create table lgquizz.TestContents(
	id_test int,
    id_problem int,
    number_of_exercises int,
    primary key(id_test,id_problem),
    foreign key (id_test) references lgquizz.Tests(id_test) on delete cascade,
    foreign key (id_problem) references lgquizz.Problems(id_problem) on delete cascade
);

create table lgquizz.TestParticipants(
	id_test int,
    id_user int,
    primary key (id_test,id_user),
    foreign key (id_test) references lgquizz.Tests(id_test) on delete cascade,
    foreign key (id_user) references lgquizz.Users(id_user) on delete cascade
);

create table lgquizz.TestResponses(
	id_test int,
    id_response int,
	id_user int,
    primary key(id_test,id_response,id_user),
    foreign key (id_test) references lgquizz.Tests(id_test) on delete cascade,
    foreign key (id_user) references lgquizz.Users(id_user) on delete cascade,
    foreign key (id_response) references lgquizz.Responses(id_response) on delete cascade
);


-- exemples taken from  Annie Heminway Practice Makes Perfect Complete French Grammar (2007 )
insert into lgquizz.Categories(`category_name`) values('Fill in the blanks'),('Multiple choice');
insert into lgquizz.Lessons(`lesson_name`) values('The present tense of regular -er verbs');
insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Mettre les verbes entre parenthèses au présent.',1,1); 
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values('Lucie $BLANK(travailler) à Lyon.',0.15,1),
																	('Mon frère et moi, nous $BLANK(accepter) votre invitation.',0.15,1),
																	('M. et Mme Benoît $BLANK(chercher) un appartement.',0.15,1),
																	('Tu $BLANK(apporter) toujours des fl eurs.',0.15,1),
																	('Vous $BLANK(bavarder) sur la terrasse.',0.15,1),
																	('Je $BLANK(commander) une soupe de légumes.',0.15,1),
																	('Ils $BLANK(habiter) en Normandie.',0.15,1),
																	('Elle $BLANK(déjeuner) avec sa belle-sœur.',0.15,1),
																	('Vous $BLANK(dessiner) très bien.',0.15,1),
																	('Nous $BLANK(visiter) le château de Fontainebleau.',0.15,1),
                                                                    ('Nous $BLANK(commencer) à huit heures le matin.',0.15,1),
																	('Vous $BLANK(avancer) rapidement.',0.15,1),
																	('Je $BLANK(déplacer) les meubles du salon.',0.15,1),
																	('Nous $BLANK(devancer) nos concurrents.',0.15,1),
																	('Nous $BLANK(annoncer) une augmentation de salaire au début de l’année.',0.15,1),
																	('Tu $BLANK(effacer) le tableau.',0.15,1),
																	('Nous $BLANK(remplacer) toute l’équipe.',0.15,1),
																	('Ils $BLANK(exercer) une grande infl uence.',0.15,1),
																	('Nous $BLANK(financer) ce projet.',0.15,1),
																	('Elle $BLANK(menacer) de partir.',0.15,1),
                                                                    ('Vous $BLANK(mélanger) les ingrédients.',0.15,1),
																	('Je $BLANK(ranger) mes aff aires.',0.15,1),
																	('Nous $BLANK(exiger) votre présence à la réunion.',0.15,1),
																	('Ils $BLANK(déménager) demain.',0.15,1),
																	('Elle $BLANK(héberger) ses amis.',0.15,1),
																	('Vous $BLANK(corriger) les exercices.',0.15,1),
																	('Nous $BLANK(manger) sur la terrasse à midi.',0.15,1),
																	('Tu $BLANK(nager) dans la piscine.',0.15,1),
																	('Nous $BLANK(encourager) ces jeunes talents.',0.15,1),
																	('Souvent, il $BLANK(changer) d’avis.',0.15,1),
                                                                    ('Il $BLANK(renouveler) son passeport.',0.15,1),
																	('Je $BLANK(emmener) ma nièce à l’opéra.',0.15,1),
																	('Vous $BLANK(acheter) un kilo de haricots.',0.15,1),
																	('Le sorcier $BLANK(ensorceler) le public.',0.15,1),
																	('Elle $BLANK(espérer) aller à Paris en mai.',0.15,1),
																	('Vous $BLANK(exagérer).',0.15,1),
																	('Elle $BLANK(s’appeler) Juliette.',0.15,1),
																	('Ces diamants $BLANK(étinceler) de mille feux.',0.15,1),
																	('Il $BLANK(répéter) mille fois la même chose.',0.15,1),
																	('Nous $BLANK(célébrer) son anniversaire.',0.15,1),
																	('Aujourd’hui, il $BLANK(acheter) du poisson au marché.',0.15,1),
																	('Ils $BLANK(travailler) le samedi.',0.15,1),
																	('Vous $BLANK(emprunter) de l’argent à la banque.',0.15,1),
																	('Tu $BLANK(aimer) voyager en bateau.',0.15,1),
																	('Nous $BLANK(renoncer) à notre projet.',0.15,1),
																	('Je $BLANK(habiter) au dixième étage.',0.15,1),
																	('L’après-midi, elle $BLANK(préférer) aller dans le parc.',0.15,1),
																	('Comment $BLANK(s’appeler) sa sœur?',0.15,1),
																	('De temps en temps, nous $BLANK(bavarder) pendant la pause-café.',0.15,1),
																	('Il vous $BLANK(rappeler) avant midi.',0.15,1)
                                                                    ;
insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Traduire en français.',1,1);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values('We refuse the invitation.\n$BLANK',0.15,2),
																	('She cancels the trip.\n$BLANK',0.15,2),
																	('He speaks French.\n$BLANK',0.15,2),
																	('You bring some flowers. (formal)\n$BLANK',0.15,2),
																	('I cut the bread.\n$BLANK',0.15,2),
																	('They are having lunch with Julie.\n$BLANK',0.15,2),
																	('He borrows ten euros.\n$BLANK',0.15,2),
																	('I order a dessert.\n$BLANK',0.15,2),
																	('You study Russian. (informal)\n$BLANK',0.15,2),
																	('They are looking for a good restaurant.\n$BLANK',0.15,2)
                                                                    ;
                                                                    
insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Reformuler les phrases en utilisant être en train de + infinitif.',1,1);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('Nous chantons une chanson.\n$BLANK(50)',0.15,3),
																	('Elle dessine un mouton.\n$BLANK(50)',0.15,3),
																	('Je travaille dans la cuisine.\n$BLANK(50)',0.15,3),
																	('Tu eff aces le tableau.\n$BLANK(50)',0.15,3),
																	('Vous étudiez l’histoire européenne.\n$BLANK(50)',0.15,3),
																	('Nous bavardons dans le jardin.\n$BLANK(50)',0.15,3),
																	('Il corrige les copies.\n$BLANK(50)',0.15,3),
																	('Tu laves la chemise.\n$BLANK(50)',0.15,3),
																	('Je range mes aff aires.\n$BLANK(50)',0.15,3),
																	('Elle mange une omelette aux champignons.\n$BLANK(50)',0.15,3)
                                                                    ;                                                                    

insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Répondre aux questions en utilisant le présent et depuis',1,1);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('Depuis combien de temps chante-t-elle dans cette chorale? (trois ans)\n$BLANK(50)',0.15,4),
																	('Depuis combien de temps partages-tu cet appartement? (six mois)\n$BLANK(50)',0.15,4),
																	('Depuis combien de temps nage-t-il dans cette piscine? (un mois)\n$BLANK(50)',0.15,4),
																	('Depuis quand habitez-vous à Montpellier? (2004)\n$BLANK(50)',0.15,4),
																	('Depuis combien de temps possède-t-il cette propriété? (dix ans)\n$BLANK(50)',0.15,4),
																	('Depuis combien de temps regardez-vous cette émission? (des années)\n$BLANK(50)',0.15,4),
																	('Depuis quand travaille-t-il dans cette entreprise? (2002)\n$BLANK(50)',0.15,4),
																	('Depuis combien de temps portez-vous des lunettes?\n$BLANK(50)',0.15,4),
																	('Depuis quand est-il président? (2005)\n$BLANK(50)',0.15,4),
																	('Depuis combien de temps ce magasin est-il fermé? (deux mois)\n$BLANK(50)',0.15,4)
                                                                    ;
                                                                    
insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Traduire les phrases suivantes en utilisant vous et l’inversion si nécessaire.',1,1);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values('I study French.\n$BLANK(50)',0.15,5),
																	('I spell my name.\n$BLANK(50)',0.15,5),
																	('They are moving tomorrow.\n$BLANK(50)',0.15,5),
																	('She likes to travel by boat.\n$BLANK(50)',0.15,5),
																	('How long have you been studying French?\n$BLANK(50)',0.15,5),
																	('You repeat the sentence. (informal)\n$BLANK(50)',0.15,5),
																	('We are fi nancing the project.\n$BLANK(50)',0.15,5),
																	('She cancels the meeting.\n$BLANK(50)',0.15,5),
																	('How long have you been living in this house?\n$BLANK(50)',0.15,5),
																	('I weigh the vegetables.\n$BLANK(50)',0.15,5)
                                                                    ; 

insert into lgquizz.Lessons(`lesson_name`) values('The present tense of -ir and -re verbs');
insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Mettre les verbes entre parenthèses au présent.',2,1);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('Nous $BLANK(10)(cueillir) des fl eurs dans le jardin.',0.15,6),
																	('Ils $BLANK(10)(finir) à dix-huit heures.',0.15,6),
																	('Je $BLANK(10)(remplir) les verres des invités.',0.15,6),
																	('Nous $BLANK(10)(investir) dans l’immobilier.',0.15,6),
																	('Ils $BLANK(10)(mentir) à la police.',0.15,6),
																	('Tu $BLANK(10)(ouvrir) les fenêtres du salon.',0.15,6),
																	('Vous $BLANK(10)(réfléchir) à leur proposition.',0.15,6),
																	('Je $BLANK(10)(sentir) les bonnes odeurs de la cuisine.',0.15,6),
																	('Ils $BLANK(10)(offrir) toujours les mêmes fleurs.',0.15,6),
																	('Il $BLANK(10)(mourir) de faim.',0.15,6)
                                                                    ;
insert into lgquizz.Responses(`id_exercise`,`content`,`percentage`) values ('1','travaille','1'),
																			('2','acceptons','1'),
																			('3','cherchent','1'),
																			('4','apportes ','1'),
																			(5,'bavardez','1'),
																			(6,'commande','1'),
																			(7,'habitent','1'),
																			(8,'déjeune','1'),
																			(9,'dessinez','1'),
																			(10,'visitons','1'),
																			(51,'Nous refusons l’invitation.','1'),
																			(52,'Elle annule le voyage.','1'), 
																			(53,'Il parle français.','1'),
																			(54,'Vous apportez des fleurs.','1'), 
																			(55,'Je coupe le pain.','1'),
																			(56,'Ils (Elles) déjeunent avec Julie.','1'), 
																			(57,'Il emprunte dix euros.','1'), 
																			(58,'Je commande un dessert.','1'), 
																			(59,'Tu étudies le russe.','1'), 
																			(60,'Ils (Elles) cherchent un bon restaurant.','1'),
																			(11,'commençons','1'),
																			(12,'avancez','1'), 
																			(13,'déplace','1'),
																			(14,'devançons','1'),
																			(15,'annonçons','1'), 
																			(16,'effaces','1'),
																			(17,'remplaçons','1'),
																			(18,'exercent','1'),
																			(19,'finançons','1'),
																			(20,'menace','1'),
																			(21,'mélangez','1'),
																			(22,'range','1'),
																			(23,'exigeons','1'),
																			(24,'déménagent','1'),
																			(25,'héberge','1'),
																			(26,'corrigez','1'),
																			(27,'mangeons','1'),
																			(28,'nages','1'),
																			(29,'encourageons','1'), 
																			(30,'change','1'),
																			(31,'renouvelle','1'),
																			(32,'emmène','1'),
																			(33,'achetez','1'),
																			(34,'ensorcelle','1'),
																			(35,'espère','1'),
																			(36,'exagérez','1'),
																			(37,'s’appelle','1'),
																			(38,'étincellent','1'),
																			(39,'répète','1'),
																			(40,'célébrons','1'),
																			(41,'achète','1'),
																			(42,'travaillent','1'),
																			(43,'empruntez','1'),
																			(44,'aimes','1'),
																			(45,'renonçons','1'),
																			(46,'J’habite','1'),
																			(47,'préfère','1'),
																			(48,'s’appelle','1'),
																			(49,'bavardons','1'),
																			(50,'rappelle','1'),
																			(61,'Nous sommes en train de chanter une chanson.',1),
																			(62,'Elle est en train de dessiner un mouton.',1),
																			(63,'Je suis en train de travailler dans la cuisine.',1),
																			(64,'Tu es en train d’eff acerle tableau.',1),
																			(65,'Vous êtes en train d’étudier l’histoire européenne.',1),
																			(66,'Nous sommes entrain de bavarder dans le jardin.',1),
																			(67,'Il est en train de corriger les copies.',1),
																			(68,'Tu es en train de laver la chemise.',1),
																			(69,'Je suis en train de ranger mes aff aires.',1),
																			(70,'Elle est en train de manger une omelette aux champignons.',1),
																			(71,'Elle chante dans cette chorale depuis trois ans.',1),
																			(72,'Je partage cet appartement depuis six mois.',1),
																			(73,'Il nage dans cette piscine depuis un mois.',1),
																			(74,'J’habite à Montpellier depuis 2004.',1),
																			(75,'Il possède cette propriété depuis dix ans.',1),
																			(76,'Je regarde cette émission depuis des années.',1),
																			(77,'Il travaille dans cette entreprise depuis 2002.',1),
																			(78,'Je porte des lunettes depuis dix ans.',1),
																			(79,'Il est président depuis 2005.',1),
																			(80,'Ce magasin est fermé depuis deux mois.',1),
																			(81,'J’étudie le français.',1),
																			(82,'J’épelle mon nom.',1),
																			(83,'Ils (Elles) déménagent demain.',1),
																			(84,'Elle aime voyager en bateau.',1),
																			(85,'Depuis combien de temps étudiez-vous le français?',1),
																			(86,'Tu répètes la phrase.',1),
																			(87,'Nous fi nançons le projet.',1),
																			(88,'Elle annule la réunion.',1),
																			(89,'Depuis combien de temps habitez-vous dans cette maison?',1), 
																			(90,'Je pèse les légumes',1),
																			(91,'cueillons',1),
																			(92,'finissent',1),
																			(93,'remplis',1),
																			(94,'investissons',1),
																			(95,'mentent',1),
																			(96,'ouvres',1),
																			(97,'réfléchissez',1),
																			(98,'sens',1),
																			(99,'offrent',1),
																			(100,'meurt',1);                                                                            
insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Traduire les phrases suivantes en utilisant vous si nécessaire.',2,1);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ("We are leaving at ten.\n$BLANK(50)",0.15,7),
																	("She opens the door.\n$BLANK(50)",0.15,7),
																	("You pick some fl owers in Florence’s garden.\n$BLANK(50)",0.15,7),
																	("The car is slowing down.\n$BLANK(50)",0.15,7),
																	("We are going out tonight.\n$BLANK(50)",0.15,7),
																	("She seizes the opportunity.\n$BLANK(50)",0.15,7),
																	("She blushes easily.\n$BLANK(50)",0.15,7),
																	("They run fast.\n$BLANK(50)",0.15,7),
																	("She solves the mystery.1\n$BLANK(50)",0.15,7),
																	("They sleep in Sonia’s bedroom.\n$BLANK(50)",0.15,7);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('Nous (répondre) $BLANK(50) aux questions du professeur de français.',0.15,6),
																	('La presse anglaise (répandre) $BLANK(50) une rumeur inquiétante.',0.15,6),
																	('Vous (rendre) $BLANK(50) les livres à la bibliothèque.',0.15,6),
																	('Ils (vendre) $BLANK(50) des fruits et légumes au marché.',0.15,6),
																	('Je (descendre) $BLANK(50) l’escalier à toute vitesse.',0.15,6),
																	('Tu (attendre) $BLANK(50) l’autobus depuis dix minutes.',0.15,6),
																	('Il me (tendre) $BLANK(50) la main pour me dire bonjour.',0.15,6),
																	('Elle (perdre) $BLANK(50) toujours ses clés.',0.15,6),
																	('Il (prétendre) $BLANK(50) être le plus intelligent.1',0.15,6),
																	('Ils (étendre) $BLANK(50) leur action à d’autres domaines.',0.15,6),
                                                                    ('Nous (prendre) $BLANK(20) le petit déjeuner à huit heures.',0.15,6),
																	('Il (entreprendre) $BLANK(20) toujours des choses dangereuses.',0.15,6),
																	('Je (apprendre) $BLANK(20) l’allemand.',0.15,6),
																	('Vous (comprendre) $BLANK(20) son hésitation.',0.15,6),
																	('Ils (apprendre) $BLANK(20) à conduire.',0.15,6),
																	('Il (surprendre) $BLANK(20) le secret.',0.15,6),
																	('Vous (prendre) $BLANK(20) de longues vacances.',0.15,6),
																	('Nous (comprendre) $BLANK(20) le chinois.',0.15,6),
																	('Tu (prendre) $BLANK(20) une autre direction.1',0.15,6),
																	('Elle (comprendre) $BLANK(20) tout.',0.15,6)
                                                                    ;
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('He is learning Chinese.\n$BLANK(50)',0.15,7),
																	('She takes the subway every day.\n$BLANK(50)',0.15,7),
																	('He often loses his keys.\n$BLANK(50)',0.15,7),
																	('I can hear Pierre on the street.\n$BLANK(50)',0.15,7),
																	('He claims to be the king’s brother.\n$BLANK(50)',0.15,7),
																	('You answer quickly.\n$BLANK(50)',0.15,7),
																	('She sells fl owers.\n$BLANK(50)',0.15,7),
																	('We go down the Champs-Élysées.\n$BLANK(50)',0.15,7),
																	('I am going down.1\n$BLANK(50)',0.15,7),
																	('We are waiting for an answer.\n$BLANK(50)',0.15,7);
															
insert into lgquizz.Lessons(`lesson_name`) values('The interrogative form');
insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Mettre les phrases suivantes à la forme interrogative en utilisant l’inversion.',3,1);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('Ils remplissent les formulaires.\n$BLANK(50)',0.15,8),
																	('Il réfl échit au problème.\n$BLANK(50)',0.15,8),
																	('Vous aimez aller au théâtre.\n$BLANK(50)',0.15,8),
																	('Elle préfère voyager en Italie.\n$BLANK(50)',0.15,8),
																	('Tu écoutes le discours du président.\n$BLANK(50)',0.15,8),
																	('Ils infl uencent le public.\n$BLANK(50)',0.15,8),
																	('Elle annule son voyage au Brésil.\n$BLANK(50)',0.15,8),
																	('Tu travailles le jeudi.\n$BLANK(50)',0.15,8),
																	('Vous apportez un nouveau livre.1\n$BLANK(50)',0.15,8),
																	('Elle agrandit les photos.\n$BLANK(50)',0.15,8);
insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Mettre les phrases suivantes à la forme interrogative en utilisant la forme est-ce que.',3,1);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('Ils parlent de la nouvelle transaction.\n$BLANK(50)',0.15,9),
																	('Elle apprend le portugais.\n$BLANK(50)',0.15,9),
																	('Vous commandez une bouteille de vin blanc.\n$BLANK(50)',0.15,9),
																	('Tu demandes une augmentation de salaire.\n$BLANK(50)',0.15,9),
																	('Ils fi nancent un grand projet.\n$BLANK(50)',0.15,9),
																	('Vous choisissez une autre direction.\n$BLANK(50)',0.15,9),
																	('Ils fi nissent tard.\n$BLANK(50)',0.15,9),
																	('Il prétend être pauvre.\n$BLANK(50)',0.15,9),
																	('Ils défendent cette théorie.1\n$BLANK(50)',0.15,9),
																	('Vous descendez par l’escalier.\n$BLANK(50)',0.15,9);
insert into lgquizz.Lessons(`lesson_name`,`lesson_description`) values('The negative form','To make a sentence negative, you simply place ne... pas around the verb.\n If the ne precedes a verb starting with a vowel or a mute h, ne becomes n’.\n Aside from ne... pas, there are other negations, constructed in the same way.\n Il n’attend personne.
																		He is not waiting for anybody.
																		Tu ne voyages jamais en hiver.
																		You never travel during the winter.
																		Il n’a plus de patience.
																		He has no patience left.');
insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Mettre les phrases suivantes à la forme négative.',4,1);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('Il encourage ses employés.\n$BLANK(50)',0.15,10),
																	('Ils visitent le musée.\n$BLANK(50)',0.15,10),
																	('Tu gagnes à la loterie.\n$BLANK(50)',0.15,10),
																	('Elle enlève son chapeau.\n$BLANK(50)',0.15,10),
																	('Vous exprimez vos opinions.\n$BLANK(50)',0.15,10),
																	('Tu pèses les fruits.\n$BLANK(50)',0.15,10),
																	('Il danse la valse.\n$BLANK(50)',0.15,10),
																	('Vous corrigez les copies des étudiants.\n$BLANK(50)',0.15,10),
																	('Nous étudions l’arabe.1\n$BLANK(50)',0.15,10),
																	('Il maigrit en vacances.\n$BLANK(50)',0.15,10)
																	;
insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Traduire les phrases suivantes en utilisant vous et l’inversion si nécessaire.',4,1);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('I am learning Japanese.\n$BLANK(50)',0.15,11),
																	('He does not speak Italian.\n$BLANK(50)',0.15,11),
																	('She eats neither meat nor cheese.\n$BLANK(50)',0.15,11),
																	('They never listen to anybody.\n$BLANK(50)',0.15,11),
																	('You work late.\n$BLANK(50)',0.15,11),
																	('They like neither tea nor coff ee.\n$BLANK(50)',0.15,11),
																	('Do you understand the question?\n$BLANK(50)',0.15,11),
																	('We pick flowers in the garden.\n$BLANK(50)',0.15,11),
																	('He never takes off his hat.1\n$BLANK(50)',0.15,11),
																	('She never lies.\n$BLANK(50)',0.15,11);
insert into lgquizz.Lessons(`lesson_name`) values('To be and to have');
insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Mettre au présent les verbes entre parenthèses.',5,1);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('Le château (être) $BLANK(20) vieux.',0.15,12),
																	('Nous (être) $BLANK(20) libres demain soir.',0.15,12),
																	('Les produits (être) $BLANK(20) beaucoup trop chers.',0.15,12),
																	('Tu (être) $BLANK(20) plus jeune que lui?',0.15,12),
																	('Elles (être) $BLANK(20) vraiment charmantes.',0.15,12),
																	('Vous (être) $BLANK(20) occupé cet après-midi?',0.15,12),
																	('Ce (être) $BLANK(20) un nouveau livre.',0.15,12),
																	('Leurs méthodes (ne pas être) $BLANK(20) très effi caces.',0.15,12),
																	('Est-ce qu’il (être) $BLANK(20) aussi amusant que son frère?1',0.15,12),
																	('Je (être) $BLANK(20) un peu en retard.',0.15,12);
insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Répondre aux questions à la forme affirmative.',5,1);                                                                   
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('Est-ce qu’ils sont en retard?\n$BLANK(50)',0.15,13),
																	('Le climat est sec?\n$BLANK(50)',0.15,13),
																	('Êtes-vous libre ce soir?\n$BLANK(50)',0.15,13),
																	('Est-il heureux?\n$BLANK(50)',0.15,13),
																	('Est-ce qu’elle est sympathique?\n$BLANK(50)',0.15,13),
																	('Ce restaurant français est cher?\n$BLANK(50)',0.15,13),
																	('Êtes-vous fatigué?\n$BLANK(50)',0.15,13),
																	('Est-ce que nous sommes à la bonne adresse?\n$BLANK(50)',0.15,13),
																	('Ce fi lm est amusant?1\n$BLANK(50)',0.15,13),
																	('Le musée est ouvert?\n$BLANK(50)',0.15,13);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('Nous (avoir) $BLANK(20) quelques minutes.',0.15,12),
																	('Tu (ne pas avoir) $BLANK(20) assez d’arguments.',0.15,12),
																	('Je (avoir) $BLANK(20) une grande estime pour lui.',0.15,12),
																	('Vous (avoir) $BLANK(20) des amis à Londres?',0.15,12),
																	('Elle (avoir) $BLANK(20) beaucoup de chance dans les aff aires.',0.15,12),
																	('Ils (avoir) $BLANK(20) une réunion à quinze heures.',0.15,12),
																	('Tu (avoir) $BLANK(20) une maison à la campagne?',0.15,12),
																	('Nous (ne pas avoir) $BLANK(20) besoin de son aide.',0.15,12),
																	('Vous (ne pas avoir) $BLANK(20) toujours raison.1',0.15,12),
																	('Je (avoir) $BLANK(20) froid.',0.15,12);
insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Traduire les phrases suivantes en utilisant vous et l’inversion si nécessaire.',5,1);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('I am tired.\n$BLANK(50)',0.15,14),
																	('He is very hungry.\n$BLANK(50)',0.15,14),
																	('They are always right.\n$BLANK(50)',0.15,14),
																	('Are they French?\n$BLANK(50)',0.15,14),
																	('Are you afraid of his reaction?\n$BLANK(50)',0.15,14),
																	('He is ashamed.\n$BLANK(50)',0.15,14),
																	('They have a dog.\n$BLANK(50)',0.15,14),
																	('She has a new hat.\n$BLANK(50)',0.15,14),
																	('It’s very expensive.1\n$BLANK(50)',0.15,14),
																	('Close the window. We are cold.\n$BLANK(50)',0.15,14);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('Est-ce que vous (savoir) $BLANK(20) jouer au poker?',0.15,12),
																	('Je (savoir) $BLANK(20) que Laurent est un bon musicien.',0.15,12),
																	('Elle (ne pas savoir) $BLANK(20) s’il travaille lundi.',0.15,12),
																	('Nous (savoir) $BLANK(20) utiliser cet ordinateur.',0.15,12),
																	('Tu (savoir) $BLANK(20) parler espagnol?',0.15,12),
																	('Est-ce que tu (savoir) $BLANK(20) parler anglais?',0.15,12),
																	('Il (ne pas savoir) $BLANK(20) faire la cuisine.',0.15,12),
																	('(Savoir) $BLANK(20)-vous quand ils partent?',0.15,12),
																	('Tu (savoir) $BLANK(20) si ce restaurant est cher?1',0.15,12),
																	('Vous (savoir) $BLANK(20) où se trouve la Bastille?',0.15,12);
insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Conjuguer le verbe connaître au présent.',5,1);
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('Ils $BLANK(20) bien la Normandie.',0.15,15),
																	('Nous $BLANK(20) Julien depuis trois ans.',0.15,15),
																	('Ce nouveau club $BLANK(20) un grand succès.',0.15,15),
																	('Je $BLANK(20) ce fait.',0.15,15),
																	('Cet artisan $BLANK(20) son métier.',0.15,15),
																	('Vous $BLANK(20) cette chanson?',0.15,15),
																	('Est-ce que vous $BLANK(20) un bon restaurant italien?',0.15,15),
																	('Je $BLANK(20) Paris comme ma poche.',0.15,15),
																	('Il $BLANK(20) cette méthode à la perfection.1',0.15,15),
																	('$BLANK(20)-vous l’œuvre de Victor Hugo?',0.15,15);
insert into lgquizz.Problems(`problem_text`,`id_lesson`,`id_category`) values('Connaître ou savoir?',5,1);                                                                    
insert into lgquizz.Exercises(`content`,`mark`,`id_problem`) values ('Est-ce que $BLANK(20) tu pourquoi il est absent?',0.15,16),
																	('Elle $BLANK(20) cette chanson par cœur.',0.15,16),
																	('Tu $BLANK(20) jouer au base-ball?',0.15,16),
																	('Nous $BLANK(20) la fi lle de José.',0.15,16),
																	('Je ne $BLANK(20) pas à quelle heure ouvre la banque.',0.15,16),
																	('Ils $BLANK(20) un bon dentiste.',0.15,16),
																	('Ce nouveau produit $BLANK(20) un grand succès sur le marché.',0.15,16),
																	('Vous $BLANK(20) Bertrand?',0.15,16),
																	('Il $BLANK(20) qu’il n’est pas qualifi é pour ce travail.1',0.15,16),
																	('Nous ne $BLANK(20) pas ce quartier.',0.15,16);
insert into lgquizz.Responses(`id_exercise`,`content`,`percentage`) values 
																	(101,'Nous partons à dix heures.',1),
																	(102,'Elle ouvre la porte.',1),
																	(103,'Vous cueillez des fl eurs dansle jardin de Florence.',1),
																	(104,'La voiture ralentit.',1),
																	(105,'Nous sortons ce soir.',1),
																	(106,'Elle saisit l’occasion.',1),
																	(107,'Elle rougit facilement.',1),
																	(108,'Ils (Elles) courent vite.',1),
																	(109,'Elle résout le mystère.1',1),
																	(110,'Ils (Elles) dorment dans la chambre de Sonia.',1),
																	(111,'répondons',1),
																	(112,'répand',1),
																	(113,'rendez',1),
																	(114,'vendent',1),
																	(115,'descends',1),
																	(116,'attends',1),
																	(117,'tend',1),
																	(118,'perd',1),
																	(119,'prétend',1),
																	(120,'étendent',1),
																	(121,'prenons',1),
																	(122,'entreprend',1),
																	(123,'apprends',1),
																	(124,'comprenez',1),
																	(125,'apprennent',1),
																	(126,'surprend',1),
																	(127,'prenez',1),
																	(128,'comprenons',1),
																	(129,'prends',1),
																	(130,'comprend',1),
																	(131,'Il apprend le chinois.',1),
																	(132,'Elle prend le métro tous les jours.',1),
																	(133,'Il perd souvent ses clés.',1),
																	(134,'J’entends Pierre dans la rue.',1),
																	(135,'Il prétend être le frère du roi.',1),
																	(136,'Vous répondez rapidement.',1),
																	(137,'Elle vend des fleurs.',1),
																	(138,'Nous descendons les Champs-Élysées.',1),
																	(139,'Je descends.',1),
																	(140,'Nous attendons une réponse.',1),
																	(141,'Remplissent-ils les formulaires?',1),
																	(142,'Réfl échit-il au problème?',1),
																	(143,'Aimez-vous aller au théâtre?',1),
																	(144,'Préfère-t-elle voyager en Italie?',1),
																	(145,'Écoutes-tu le discours du président?',1),
																	(146,'Infl uencent-ils le public?',1),
																	(147,'Annule-t-elle son voyage au Brésil?',1),
																	(148,'Travailles-tu le jeudi?',1),
																	(149,'Apportez-vous un nouveau livre?',1),
																	(150,'Agrandit-elle les photos?',1),
																	(151,'Est-ce qu’ils parlent de la nouvelle transaction?',1),
																	(152,'Est-ce qu’elle apprend le portugais?',1),
																	(153,'Est-ce quevous commandez une bouteille de vin blanc?',1),
																	(154,'Est-ce que tu demandes une augmentation de salaire?',1),
																	(155,'Est-ce qu’ils fi nancent un grand projet?',1),
																	(156,'Est-ce que vous choisissez une autre direction?',1),
																	(157,'Est-cequ’ils fi nissent tard?',1),
																	(158,'Est-ce qu’il prétend être pauvre?',1),
																	(159,'Est-ce qu’ils défendent cette théorie?',1),
																	(160,'Est-ce que vous descendez par l’escalier?',1),
																	(161,'Il n’encourage pas ses employés.',1),
																	(162,'Ils ne visitent pas le musée.',1),
																	(163,'Tu ne gagnes pas à la loterie.',1),
																	(164,'Elle n’enlève pas son chapeau.',1),
																	(165,'Vous n’exprimez pas vos opinions.',1),
																	(166,'Tu ne pèses pas les fruits.',1),
																	(167,'Il ne danse pas la valse.',1),
																	(168,'Vous ne corrigez pas les copies des étudiants.',1),
																	(169,'Nous n’étudions pas l’arabe.',1),
																	(170,'Il ne maigrit pas en vacances.',1),
																	(171,'J’apprends le japonais.',1),
																	(172,'Il ne parle pas italien.',1),
																	(173,'Elle ne mange ni viande ni fromage.',1),
																	(174,'Ils(Elles) n’écoutent jamais personne.',1),
																	(175,'Vous travaillez tard.',1),
																	(176,'Ils (Elles) n’aiment ni le thé ni le café.',1),
																	(177,'Comprenez-vous la question?',1),
																	(178,'Nous cueillons des fl eurs dans le jardin.',1),
																	(179,'Il n’enlève jamais sonchapeau.',1),
																	(180,'Elle ne ment jamais.',1),
																	(181,'est',1),
																	(182,'sommes',1),
																	(183,'sont',1),
																	(184,'es',1),
																	(185,'sont',1),
																	(186,'êtes',1),
																	(187,'C’est',1),
																	(188,'ne sont pas',1),
																	(189,'est',1),
																	(190,'suis',1),
																	(191,'Oui, ils sont en retard.',1),
																	(192,'Oui, le climat est sec.',1),
																	(193,'Oui, je suis libre ce soir.',1),
																	(194,'Oui, il est heureux.',1),
																	(195,'Oui, elle est sympathique.',1),
																	(196,'Oui, ce restaurant français est cher.',1),
																	(197,'Oui, je suis fatigué.',1),
																	(198,'Oui, vous êtes à la bonne adresse.',1),
																	(199,'Oui, ce fi lm est amusant.',1),
																	(200,'Oui, le musée est ouvert.',1),
																	(201,'avons',1),
																	(202,'n’as pas',1),
																	(203,'J’ai',1),
																	(204,'avez',1),
																	(205,'a',1),
																	(206,'ont',1),
																	(207,'as',1),
																	(208,'n’avons pas',1),
																	(209,'n’avez pas',1),
																	(210,'J’ai',1),
																	(211,'Je suis fatigué(e).',1),
																	(212,'Il a très faim.',1),
																	(213,'Ils (Elles) ont toujours raison.',1),
																	(214,'Sont-ils français? (Sont-elles françaises?)',1),
																	(215,'Avez-vous peur de sa réaction?',1),
																	(216,'Il a honte.',1),
																	(217,'Ils (Elles) ont un chien.',1),
																	(218,'Elle a un nouveau chapeau.',1),
																	(219,'C’est très cher.',1),
																	(220,'Fermez la fenêtre. Nous avons froid.',1),
																	(221,'savez',1),
																	(222,'sais',1),
																	(223,'ne sait pas',1),
																	(224,'savons',1),
																	(225,'sais',1),
																	(226,'sais',1),
																	(227,'ne sait pas',1),
																	(228,'Savez',1),
																	(229,'sais',1),
																	(230,'savez',1),
																	(231,'connaissent',1),
																	(232,'connaissons',1),
																	(233,'connaît',1),
																	(234,'connais',1),
																	(235,'connaît',1),
																	(236,'connaissez',1),
																	(237,'connaissez',1),
																	(238,'connais',1),
																	(239,'connaît',1),
																	(240,'Connaissez',1),
																	(241,'sais',1),
																	(242,'sait',1),
																	(243,'sais',1),
																	(244,'connaissons',1),
																	(245,'sais',1),
																	(246,'connaissent',1),
																	(247,'connaît',1),
																	(248,'connaissez',1),
																	(249,'sait',1),
																	(250,'connaissons',1);
 
insert into lgquizz.Tests(`test_name`,`restricted`) values ('Present verbs',false);
insert into lgquizz.TestContents(`id_test`,`id_problem`,`number_of_exercises`) values(1,1,4),(1,2,2),(1,3,5);

